insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Vinegar - White Wine', 400.48);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Shrimp - Baby, Cold Water', 753.37);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Pinot Grigio Collavini', 881.56);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Carrots - Mini Red Organic', 549.61);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lamb Tenderloin Nz Fr', 741.07);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Basil - Seedlings Cookstown', 301.64);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Potatoes - Yukon Gold, 80 Ct', 293.65);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Brandy Apricot', 409.3);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Coffee - Decafenated', 646.61);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Shrimp - Tiger 21/25', 421.14);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Coffee Swiss Choc Almond', 73.19);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tequila Rose Cream Liquor', 426.79);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Soup - Campbells Chili Veg', 647.69);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beans - Green', 674.21);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Bones, Cut - Up', 257.7);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chocolate - Milk Coating', 862.66);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cherries - Maraschino,jar', 189.9);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pie Filling - Apple', 733.78);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Vodka - Smirnoff', 179.95);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Corn Kernels - Frozen', 509.43);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beans - Yellow', 928.63);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tomatoes', 579.9);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bacardi Limon', 321.27);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chocolate - Sugar Free Semi Choc', 877.09);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chocolate Bar - Coffee Crisp', 977.37);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Eggplant - Regular', 223.59);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Oil - Hazelnut', 434.57);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cookie Chocolate Chip With', 892.72);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Turkey - Breast, Smoked', 784.13);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Jam - Apricot', 231.39);
